gnetlist: Add test for post backend loading of code.

diff --git a/gnetlist/tests/run-test b/gnetlist/tests/run-test
--- a/gnetlist/tests/run-test
+++ b/gnetlist/tests/run-test
@@ -96,6 +96,20 @@ vams-device)
     vamsmode=device
     cmd="(define generate-mode 2) (define top-attribs '(refdes=U1 device=7404 footprint=DIP14))"
     ;;
+postload)
+    "${GNETLIST}" -L "${abs_top_srcdir}/libgeda/scheme" \
+                                     -L "${abs_top_builddir}/libgeda/scheme" \
+                                     -g "geda" \
+                                     -o - \
+                                     -m "${abs_srcdir}/postload/test-postload.scm" \
+                                     ${schematic}
+    if test $? -ne 100 ; then
+        echo "FAILED: Post backend load check failed."
+        exit 1
+    else
+        exit 0
+    fi
+    ;;
 esac
 
 # run gnetlist
