Rebuilt makefiles, misc fileselect bugs fixed, added libgeda-config stuff to the utils ./configure.in

diff --git a/utils/configure b/utils/configure
--- a/utils/configure
+++ b/utils/configure
@@ -1591,6 +1591,52 @@ cat >> confdefs.h <<EOF
 EOF
 
 
+# search for libgeda-config
+# Extract the first word of "libgeda-config", so it can be a program name with args.
+set dummy libgeda-config; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:1599: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_LIBGEDACONFIG'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$LIBGEDACONFIG" in
+  /*)
+  ac_cv_path_LIBGEDACONFIG="$LIBGEDACONFIG" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_LIBGEDACONFIG="$LIBGEDACONFIG" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="${PATH}"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_LIBGEDACONFIG="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_LIBGEDACONFIG" && ac_cv_path_LIBGEDACONFIG="no"
+  ;;
+esac
+fi
+LIBGEDACONFIG="$ac_cv_path_LIBGEDACONFIG"
+if test -n "$LIBGEDACONFIG"; then
+  echo "$ac_t""$LIBGEDACONFIG" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+
+if test $LIBGEDACONFIG = "no"; then
+        { echo "configure: error: Cannot find libgeda-config -- be sure that libgeda is installed" 1>&2; exit 1; }
+fi
+
+LIBGEDA_CFLAGS=`$LIBGEDACONFIG --cflags`
+#LIBGEDA_LDFLAGS = `$LIBGEDACONFIG --libs`
+
+
 
 
 
@@ -1744,7 +1790,9 @@ s%@MAINTAINER_MODE_FALSE@%$MAINTAINER_MODE_FALSE%g
 s%@MAINT@%$MAINT%g
 s%@CC@%$CC%g
 s%@CPP@%$CPP%g
+s%@LIBGEDACONFIG@%$LIBGEDACONFIG%g
 s%@HOME@%$HOME%g
+s%@LIBGEDA_CFLAGS@%$LIBGEDA_CFLAGS%g
 
 CEOF
 EOF
