Fix several minor bugs in the testsuite.
- Make the list of arguments passed into the runtest.sh script match
what the script actually expects.

- Make the use of temp files more secure.

- Be more consistent about the usage of the build directory versus
  the source directory.

- When a single test fails, just increment a failed count and continue on.
  Don't abort until all the tests have run.

diff --git a/gsymcheck/tests/Makefile.am b/gsymcheck/tests/Makefile.am
--- a/gsymcheck/tests/Makefile.am
+++ b/gsymcheck/tests/Makefile.am
@@ -45,15 +45,22 @@ tests:
 # Cleanup
 	rm -f $(BUILDDIR)/new_*
 
+	fail=0 ; \
+	pass=0 ; \
 	for file in $(SRCDIR)/*.sym; do \
-	  $(SRCDIR)/runtest.sh $$file $(BUILDDIR) $(SRCDIR); \
+	  $(SHELL) $(SRCDIR)/runtest.sh $$file $(BUILDDIR) $(SRCDIR); \
           if [ $$? -ne 0 ]; then \
 	     echo "$$file FAILED!"; \
-             exit 1; \
+             fail=`expr $$fail + 1`; \
 	   else \
 	     echo "$$file passed."; \
+             pass=`expr $$pass + 1`; \
 	   fi; \
-	done
+	done ; \
+	echo "passed: $$pass" ; \
+	echo "failed: $$fail" ; \
+	exit $$fail
+
 
 # Cleanup
 #	rm -f $(BUILDDIR)/new_*
